DELETE FROM USUARIOS;

INSERT INTO USUARIOS (NOMBRE, CONTRASEÑA, CORREO, TIPO)
VALUES ('PEPE','PEPE01','PEPE01@GMAIL.COM','USUARIO');
INSERT INTO USUARIOS (NOMBRE, CONTRASEÑA, CORREO, TIPO)
VALUES ('NURIA','NURIA01','NURIA01@GMAIL.COM','USUARIO');
INSERT INTO USUARIOS (NOMBRE, CONTRASEÑA, CORREO, TIPO)
VALUES ('JOSE','JOSE01','JOSE01@GMAIL.COM','USUARIO');
INSERT INTO USUARIOS (NOMBRE, CONTRASEÑA, CORREO, TIPO)
VALUES ('MAR','MAR01','MAR01@GMAIL.COM','ADMIN');
INSERT INTO USUARIOS (NOMBRE, CONTRASEÑA, CORREO, TIPO)
VALUES ('LUIS','LUIS01','LUIS01@GMAIL.COM','ADMIN');
INSERT INTO USUARIOS (NOMBRE, CONTRASEÑA, CORREO, TIPO)
VALUES ('SANDRA','SANDRA01','SANDRA01@GMAIL.COM','ADMIN');


SELECT * FROM USUARIOS;