
CREATE OR REPLACE TRIGGER MINIMO_JUGADORES 
BEFORE INSERT OR UPDATE ON CONTRATOS_JUGADORES
FOR EACH ROW 
DECLARE
	ESTADO_ACTUAL SPLIT.ESTADO%TYPE;
    CURSOR C_CANTIDAD_JUGADORES IS
    SELECT 
        (SELECT 
            COUNT(ID_EQUIPO) 
        FROM CONTRATOS_PERSONAL 
        WHERE (FECHA_FIN = NULL OR FECHA_FIN > SYSDATE) AND ID_EQUIPO = E.ID GROUP BY ID_EQUIPO)
        CANTIDAD, 
        E.NOMBRE
    FROM EQUIPOS E;
BEGIN
	SELECT UPPER(ESTADO) INTO ESTADO_ACTUAL FROM SPLIT WHERE ID = (SELECT MAX(ID) FROM SPLIT);
	IF ESTADO_ACTUAL = 'CERRADO' THEN
		FOR FILA IN C_CANTIDAD_JUGADORES LOOP
            IF FILA.CANTIDAD < 8 THEN
                RAISE_APPLICATION_ERROR(-20001, 'EL QUIPO ' || FILA.NOMBRE || ' TIENE MENOS DE 8 JUGADORES');
            END IF;
        END LOOP;
	END IF;
END;
