DROP TABLE XML_JORNADA;
DROP TABLE XML_CLASIFICACION;
DROP TABLE XML_COMPLETO;
DROP TABLE USUARIOS;
DROP TABLE CONTRATOS_PERSONAL CASCADE CONSTRAINTS;
DROP TABLE PERSONALES CASCADE CONSTRAINTS;
DROP TABLE CONTRATOS_JUGADORES CASCADE CONSTRAINTS;
DROP TABLE JUGADORES CASCADE CONSTRAINTS;
DROP TABLE PARTIDOS CASCADE CONSTRAINTS;
DROP TABLE EQUIPOS CASCADE CONSTRAINTS;
DROP TABLE JORNADAS CASCADE CONSTRAINTS;
DROP TABLE SPLIT CASCADE CONSTRAINTS;
drop sequence NUM_JORNADA;



create sequence NUM_JORNADA increment by 1 start with 1 maxvalue 13 cycle nocache;
create TABLE SPLIT
(
ID NUMBER(2) GENERATED ALWAYS AS IDENTITY CONSTRAINT SPL_ID_PK PRIMARY KEY,
ANIO DATE NOT NULL,
TIPO VARCHAR2(10),
ESTADO VARCHAR2(10),

	constraint SPL_TIP_CK check (UPPER(TIPO) in ('VERANO', 'INVIERNO')),
	constraint SPL_EST_CK check (UPPER(ESTADO) in ('ABIERTO', 'CERRADO'))
);


CREATE TABLE JORNADAS 
(
ID NUMBER(2) GENERATED ALWAYS AS IDENTITY CONSTRAINT JOR_ID_PK PRIMARY KEY,
NUM_JORNADA number(2),
TIPO VARCHAR2(10),
ID_SPLIT NUMBER(2),

	constraint JOR_TIP_CK check (UPPER(TIPO) in ('NORMAL', 'PLAY-OFF')),
	constraint JOR_IDSPLIT_FK FOREIGN KEY (ID_SPLIT) REFERENCES SPLIT(ID)

);


CREATE TABLE EQUIPOS
(
	ID NUMBER(2) GENERATED ALWAYS AS IDENTITY CONSTRAINT EQU_ID_PK PRIMARY KEY,
	NOMBRE VARCHAR2(30),
	PRESUPUESTO_ANUAL NUMBER(9)
);


CREATE TABLE PARTIDOS 
(
	ID NUMBER(2) GENERATED ALWAYS AS IDENTITY CONSTRAINT PAR_ID_PK PRIMARY KEY,
	GOLES_EQUIPO1 NUMBER(2),
	GOLES_EQUIPO2 NUMBER(2),
	FECHA DATE,
	LUGAR VARCHAR2(50),
	ID_JORNADA NUMBER(2),
	ID_EQUIPO1 NUMBER(2),
	ID_EQUIPO2 NUMBER(2),

		constraint PAR_IDJORNADA_FK FOREIGN KEY (ID_JORNADA) REFERENCES JORNADAS(ID),
		constraint PAR_IDEQUIPO1_FK FOREIGN KEY (ID_EQUIPO1) REFERENCES EQUIPOS(ID),
		constraint PAR_IDEQUIPO2_FK FOREIGN KEY (ID_EQUIPO2) REFERENCES EQUIPOS(ID)
);


CREATE TABLE JUGADORES
(
	ID NUMBER(2) GENERATED ALWAYS AS IDENTITY CONSTRAINT JUG_ID_PK PRIMARY KEY,
	NOMBRE VARCHAR2(30),
	APELLIDOS VARCHAR2(50),
	DNI VARCHAR2(9),
	TELEFONO VARCHAR2(9),
	POSICION VARCHAR2(20),
    TIPO varchar2(15) NULL,
	VELOCIDAD NUMBER(2),
	FISICO NUMBER(2),
	TIRO NUMBER(2),
	PASE NUMBER(2),
	TALENTO NUMBER(2),
	DEFENSA NUMBER(2),
        
        constraint JUG_TIPO_CK check (upper(TIPO) in ('DRAFT', 'WILD-CARD')),
        constraint JUG_POS_CK check (upper(POSICION) in ('PORTERO', 'DEFENSA', 'MEDIO', 'DELANTERO')),
		constraint JUG_VEL_CK check (VELOCIDAD BETWEEN 0 AND 99),
		constraint JUG_FIS_CK check (FISICO BETWEEN 0 AND 99),
		constraint JUG_TIRO_CK check (TIRO BETWEEN 0 AND 99),
		constraint JUG_PASE_CK check (PASE BETWEEN 0 AND 99),
		constraint JUG_TALE_CK check (TALENTO BETWEEN 0 AND 99),
		constraint JUG_DEF_CK check (DEFENSA BETWEEN 0 AND 99)
);


CREATE TABLE CONTRATOS_JUGADORES
(
	ID NUMBER(2) GENERATED ALWAYS AS IDENTITY CONSTRAINT CONJUG_ID_PK PRIMARY KEY,
	ID_EQUIPO NUMBER(2),
	ID_JUGADOR NUMBER(3),
	FECHA_INICIO DATE,
	FECHA_FIN DATE,
	CLAUSULA NUMBER(9),
	DORSAL NUMBER(2),
	SUELDO NUMBER(8),

		constraint CONTRAJUG_IDEQUIPO_FK FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS(ID),
		constraint CONTRAJUG_IDJUG_FK FOREIGN KEY (ID_JUGADOR) REFERENCES JUGADORES(ID),
		constraint CONTRAJUG_CLAU_CK check (CLAUSULA > 1000000),
		constraint CONTRAJUG_DOR_CK check (DORSAL BETWEEN 0 AND 99),
		constraint CONTRAJUG_SUEL_CK check (SUELDO in (10000000, 15000000, 10500000, 22500000))
);


CREATE TABLE PERSONALES
(
	ID NUMBER(2) GENERATED ALWAYS AS IDENTITY CONSTRAINT PERS_ID_PK PRIMARY KEY,
	NOMBRE VARCHAR2(30),
	APELLIDOS VARCHAR2(50),
	DNI VARCHAR2(9),
	TELEFONO VARCHAR2(9),
	OFICIO VARCHAR2(20),

		constraint PERS_OFI_CK CHECK (UPPER(OFICIO) IN (UPPER('PROPIETARIO'), UPPER('ENTRENADOR'), UPPER('STAFF')))
);


CREATE TABLE CONTRATOS_PERSONAL
(
	ID NUMBER(2) GENERATED ALWAYS AS IDENTITY CONSTRAINT CONPER_ID_PK PRIMARY KEY,
	ID_PERSONAL NUMBER(3),
	ID_EQUIPO NUMBER(2),
	FECHA_INICIO DATE,
	FECHA_FIN DATE,
	SUELDO NUMBER(5),

		constraint CONPER_IDEQUIPO_FK FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS(ID),
		constraint CONPER_IDPERSONAL_FK FOREIGN KEY (ID_PERSONAL) REFERENCES PERSONALES(ID)
);


CREATE TABLE USUARIOS
(
	ID NUMBER(2) GENERATED ALWAYS AS IDENTITY CONSTRAINT USU_ID_PK PRIMARY KEY,
	NOMBRE VARCHAR2(30),
	CONTRASENA VARCHAR2(30),
	CORREO VARCHAR2(50),
	TIPO VARCHAR2(10),

		constraint USU_TIPO_CK CHECK (UPPER(TIPO) IN (UPPER('USUARIO'), UPPER('ADMIN')))
);


CREATE TABLE XML_COMPLETO
(
	ID NUMBER(2) GENERATED ALWAYS AS IDENTITY CONSTRAINT XMLCOM_ID_PK PRIMARY KEY,
	RESUL CLOB
);


CREATE TABLE XML_CLASIFICACION
(
	ID NUMBER(2) GENERATED ALWAYS AS IDENTITY CONSTRAINT XMLCLA_ID_PK PRIMARY KEY,
	RESUL CLOB
);


CREATE TABLE XML_JORNADA
(
	ID NUMBER(2) GENERATED ALWAYS AS IDENTITY CONSTRAINT XMLJOR_ID_PK PRIMARY KEY,
	RESUL CLOB
);