CREATE OR REPLACE PACKAGE INFORMES AS
    TYPE TCURSOR IS REF CURSOR;
    PROCEDURE INFORME_EQUIPO (C_INFORME OUT TCURSOR);
    /* Al procedimiento INFORME_PARTIDOS_POR_JORNADA se le pasará el número de
    la jornada de la que se quieran consultar los partidos. */
    PROCEDURE INFORME_PARTIDOS_POR_JORNADA (C_PARTIDOS OUT TCURSOR, NUMEROJORNADA IN NUMBER);
END INFORMES;