CREATE OR REPLACE PACKAGE BODY PAQUETE_XML AS

    PROCEDURE GENERAR_XML_JORNADAS AS
    BEGIN
        NULL;
    END XML_JORNADAS;
    PROCEDURE GENERAR_XML_CLASIFICACIO AS 
    QRYCTX DBMS_XMLGEN.CTXHANDLE;
        result CLOB;
    BEGIN
        QRYCTX := DBMS_XMLGEN.NEWCONTEXT('SELECT * FROM CLASIFICACION');
        DBMS_XMLGEN.SETROWSETTAG(QRYCTX, 'CLASIFICACION');
        DBMS_XMLGEN.SETROWTAG(QRYCTX, 'EQUIPO');
        DBMS_XMLGEN.SETNULLHANDLING(QRYCTX, 2);
        result := DBMS_XMLGEN.GETXML(QRYCTX);
        INSERT INTO XML_CLASIFICACION (RESUL) VALUES (result);
        DBMS_XMLGEN.CLOSECONTEXT(QRYCTX);
    END GENERAR_XML_CLASIFICACIO;
    
END PAQUETE_XML;
