CREATE OR REPLACE PACKAGE BODY GESTION_CALNEDARIO AS

    PROCEDURE GENERAR_CALENDARIO AS
    BEGIN
        FOR I IN 1..11 LOOP
            INSERT INTO JORNADAS VALUES (I,'NORMAL',(SELECT MAX(ID) FROM SPLIT));
        END LOOP;
        
    END GENERAR_CALENDARIO;
    
    
END GESTION_CALENDADRIO;