SET SERVEROUTPUT ON;

DECLARE
C_INFORME INFORMES.TCURSOR;
V_TIPOFILA V_INFO_EQUIPOS%ROWTYPE;
BEGIN
    
    INFORMES.INFORME_EQUIPO(C_INFORME);
    
    LOOP
        FETCH C_INFORME INTO V_TIPOFILA;
        EXIT WHEN C_INFORME%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('Presupuesto_anual: ' || V_TIPOFILA.PRESUPUESTO_ANUAL ||
            ', entrenador: ' || V_TIPOFILA.ENTRENADOR ||
            ', presidente: ' || V_TIPOFILA.PRESIDENTE ||
            ', cantidad_jugadores: ' || V_TIPOFILA.CANTIDADJUGADORES ||
            ', nombre_jugador: ' || V_TIPOFILA.NOMBRE_JUGADOR ||
            ', apellido_jugador: ' || V_TIPOFILA.APELLIDO_JUGADOR ||
            ', posicion_jugador: ' || V_TIPOFILA.POSICION ||
            ', tipo_jugador: ' || V_TIPOFILA.TIPO ||
            ', velocidad_jugador: ' || V_TIPOFILA.VELOCIDAD ||
            ', fisico_jugador: ' || V_TIPOFILA.FISICO ||
            ', tiro_jugador: ' || V_TIPOFILA.TIRO ||
            ', pase_jugador: ' || V_TIPOFILA.PASE ||
            ', talento_jugador: ' || V_TIPOFILA.TALENTO ||
            ', defensa_jugador: ' || V_TIPOFILA.DEFENSA ||
            ', sueldo_jugador: ' || V_TIPOFILA.SUELDO);
    END LOOP;
    CLOSE C_INFORME;
END;

/* RESULTADOS

Presupuesto_anual: 2000000, entrenador: Julio, presidente: Iker, cantidad_jugadores: 8, nombre_jugador: Ricardo, apellido_jugador: López, posicion_jugador: PORTERO, tipo_jugador: DRAFT, velocidad_jugador: 0, fisico_jugador: 0, tiro_jugador: 0, pase_jugador: 0, talento_jugador: 99, defensa_jugador: 99, sueldo_jugador: 10000000
Presupuesto_anual: 2000000, entrenador: Julio, presidente: Iker, cantidad_jugadores: 8, nombre_jugador: Román, apellido_jugador: Alegre, posicion_jugador: DEFENSA, tipo_jugador: DRAFT, velocidad_jugador: 73, fisico_jugador: 71, tiro_jugador: 68, pase_jugador: 76, talento_jugador: 86, defensa_jugador: 66, sueldo_jugador: 22500000
Presupuesto_anual: 2000000, entrenador: Julio, presidente: Iker, cantidad_jugadores: 8, nombre_jugador: Manuel, apellido_jugador: Sorroche, posicion_jugador: DELANTERO, tipo_jugador: DRAFT, velocidad_jugador: 93, fisico_jugador: 74, tiro_jugador: 87, pase_jugador: 58, talento_jugador: 78, defensa_jugador: 73, sueldo_jugador: 15000000
Presupuesto_anual: 2000000, entrenador: Julio, presidente: Iker, cantidad_jugadores: 8, nombre_jugador: Marino, apellido_jugador: Gómez, posicion_jugador: DELANTERO, tipo_jugador: DRAFT, velocidad_jugador: 73, fisico_jugador: 59, tiro_jugador: 81, pase_jugador: 83, talento_jugador: 68, defensa_jugador: 69, sueldo_jugador: 15000000
Presupuesto_anual: 2000000, entrenador: Julio, presidente: Iker, cantidad_jugadores: 8, nombre_jugador: Juan, apellido_jugador: Sauras, posicion_jugador: DEFENSA, tipo_jugador: DRAFT, velocidad_jugador: 73, fisico_jugador: 69, tiro_jugador: 69, pase_jugador: 62, talento_jugador: 65, defensa_jugador: 82, sueldo_jugador: 10500000
Presupuesto_anual: 2000000, entrenador: Julio, presidente: Iker, cantidad_jugadores: 8, nombre_jugador: Alexander, apellido_jugador: Pluvins, posicion_jugador: MEDIO, tipo_jugador: DRAFT, velocidad_jugador: 72, fisico_jugador: 58, tiro_jugador: 78, pase_jugador: 70, talento_jugador: 87, defensa_jugador: 71, sueldo_jugador: 22500000
Presupuesto_anual: 2000000, entrenador: Julio, presidente: Iker, cantidad_jugadores: 8, nombre_jugador: Martin, apellido_jugador: Rivero, posicion_jugador: MEDIO, tipo_jugador: DRAFT, velocidad_jugador: 73, fisico_jugador: 64, tiro_jugador: 82, pase_jugador: 60, talento_jugador: 87, defensa_jugador: 75, sueldo_jugador: 22500000
Presupuesto_anual: 2000000, entrenador: Julio, presidente: Iker, cantidad_jugadores: 8, nombre_jugador: Günter, apellido_jugador: Tremiño, posicion_jugador: DELANTERO, tipo_jugador: DRAFT, velocidad_jugador: 71, fisico_jugador: 76, tiro_jugador: 83, pase_jugador: 55, talento_jugador: 78, defensa_jugador: 71, sueldo_jugador: 10000000
Presupuesto_anual: 2000000, entrenador: Sergio, presidente: Juan, cantidad_jugadores: 10, nombre_jugador: Fernando, apellido_jugador: Hernández, posicion_jugador: MEDIO, tipo_jugador: WILD-CARD, velocidad_jugador: 99, fisico_jugador: 99, tiro_jugador: 99, pase_jugador: 99, talento_jugador: 99, defensa_jugador: 99, sueldo_jugador: 10500000
Presupuesto_anual: 2000000, entrenador: Sergio, presidente: Juan, cantidad_jugadores: 10, nombre_jugador: Daniel, apellido_jugador: Pérez, posicion_jugador: PORTERO, tipo_jugador: DRAFT, velocidad_jugador: 0, fisico_jugador: 0, tiro_jugador: 0, pase_jugador: 0, talento_jugador: 99, defensa_jugador: 99, sueldo_jugador: 15000000
Presupuesto_anual: 2000000, entrenador: Sergio, presidente: Juan, cantidad_jugadores: 10, nombre_jugador: Zaza, apellido_jugador: Galvany, posicion_jugador: MEDIO, tipo_jugador: DRAFT, velocidad_jugador: 73, fisico_jugador: 63, tiro_jugador: 86, pase_jugador: 87, talento_jugador: 81, defensa_jugador: 90, sueldo_jugador: 10000000
Presupuesto_anual: 2000000, entrenador: Sergio, presidente: Juan, cantidad_jugadores: 10, nombre_jugador: Andrés, apellido_jugador: Serrano, posicion_jugador: DEFENSA, tipo_jugador: DRAFT, velocidad_jugador: 74, fisico_jugador: 69, tiro_jugador: 69, pase_jugador: 71, talento_jugador: 63, defensa_jugador: 77, sueldo_jugador: 15000000
Presupuesto_anual: 2000000, entrenador: Sergio, presidente: Juan, cantidad_jugadores: 10, nombre_jugador: Bernat, apellido_jugador: Rovira, posicion_jugador: MEDIO, tipo_jugador: DRAFT, velocidad_jugador: 73, fisico_jugador: 64, tiro_jugador: 82, pase_jugador: 94, talento_jugador: 79, defensa_jugador: 64, sueldo_jugador: 10000000
Presupuesto_anual: 2000000, entrenador: Sergio, presidente: Juan, cantidad_jugadores: 10, nombre_jugador: Trillus, apellido_jugador: Martínez, posicion_jugador: DELANTERO, tipo_jugador: WILD-CARD, velocidad_jugador: 99, fisico_jugador: 99, tiro_jugador: 99, pase_jugador: 99, talento_jugador: 99, defensa_jugador: 99, sueldo_jugador: 15000000
Presupuesto_anual: 2000000, entrenador: Sergio, presidente: Juan, cantidad_jugadores: 10, nombre_jugador: Jorquera, apellido_jugador: Garcia, posicion_jugador: DEFENSA, tipo_jugador: DRAFT, velocidad_jugador: 74, fisico_jugador: 69, tiro_jugador: 70, pase_jugador: 83, talento_jugador: 66, defensa_jugador: 71, sueldo_jugador: 10000000
Presupuesto_anual: 2000000, entrenador: Sergio, presidente: Juan, cantidad_jugadores: 10, nombre_jugador: Gilles, apellido_jugador: Vidal, posicion_jugador: MEDIO, tipo_jugador: DRAFT, velocidad_jugador: 82, fisico_jugador: 58, tiro_jugador: 65, pase_jugador: 81, talento_jugador: 81, defensa_jugador: 73, sueldo_jugador: 10500000
Presupuesto_anual: 2000000, entrenador: Sergio, presidente: Juan, cantidad_jugadores: 10, nombre_jugador: Jadir, apellido_jugador: Cirera, posicion_jugador: DEFENSA, tipo_jugador: DRAFT, velocidad_jugador: 72, fisico_jugador: 55, tiro_jugador: 67, pase_jugador: 57, talento_jugador: 58, defensa_jugador: 68, sueldo_jugador: 10000000
Presupuesto_anual: 2000000, entrenador: Sergio, presidente: Juan, cantidad_jugadores: 10, nombre_jugador: Roger, apellido_jugador: Bonet, posicion_jugador: MEDIO, tipo_jugador: DRAFT, velocidad_jugador: 71, fisico_jugador: 75, tiro_jugador: 73, pase_jugador: 73, talento_jugador: 85, defensa_jugador: 68, sueldo_jugador: 22500000
Presupuesto_anual: 2000000, entrenador: Juan, presidente: Adri, cantidad_jugadores: 8, nombre_jugador: José, apellido_jugador: Figueiras, posicion_jugador: PORTERO, tipo_jugador: DRAFT, velocidad_jugador: 0, fisico_jugador: 0, tiro_jugador: 0, pase_jugador: 0, talento_jugador: 99, defensa_jugador: 99, sueldo_jugador: 22500000
Presupuesto_anual: 2000000, entrenador: Juan, presidente: Adri, cantidad_jugadores: 8, nombre_jugador: Jacobo, apellido_jugador: Fernández, posicion_jugador: DELANTERO, tipo_jugador: DRAFT, velocidad_jugador: 86, fisico_jugador: 68, tiro_jugador: 84, pase_jugador: 81, talento_jugador: 84, defensa_jugador: 67, sueldo_jugador: 10500000
Presupuesto_anual: 2000000, entrenador: Juan, presidente: Adri, cantidad_jugadores: 8, nombre_jugador: Mase, apellido_jugador: Massegú, posicion_jugador: DEFENSA, tipo_jugador: DRAFT, velocidad_jugador: 71, fisico_jugador: 76, tiro_jugador: 78, pase_jugador: 83, talento_jugador: 74, defensa_jugador: 79, sueldo_jugador: 15000000
Presupuesto_anual: 2000000, entrenador: Juan, presidente: Adri, cantidad_jugadores: 8, nombre_jugador: Edel, apellido_jugador: Beguer, posicion_jugador: DELANTERO, tipo_jugador: DRAFT, velocidad_jugador: 73, fisico_jugador: 57, tiro_jugador: 84, pase_jugador: 66, talento_jugador: 86, defensa_jugador: 71, sueldo_jugador: 15000000
Presupuesto_anual: 2000000, entrenador: Juan, presidente: Adri, cantidad_jugadores: 8, nombre_jugador: Joan, apellido_jugador: Ros, posicion_jugador: MEDIO, tipo_jugador: DRAFT, velocidad_jugador: 72, fisico_jugador: 78, tiro_jugador: 86, pase_jugador: 75, talento_jugador: 83, defensa_jugador: 80, sueldo_jugador: 10500000
Presupuesto_anual: 2000000, entrenador: Juan, presidente: Adri, cantidad_jugadores: 8, nombre_jugador: Pau, apellido_jugador: Ruiz, posicion_jugador: DEFENSA, tipo_jugador: DRAFT, velocidad_jugador: 72, fisico_jugador: 56, tiro_jugador: 76, pase_jugador: 68, talento_jugador: 74, defensa_jugador: 76, sueldo_jugador: 10500000
Presupuesto_anual: 2000000, entrenador: Juan, presidente: Adri, cantidad_jugadores: 8, nombre_jugador: Oiher, apellido_jugador: Olaechea, posicion_jugador: DELANTERO, tipo_jugador: DRAFT, velocidad_jugador: 81, fisico_jugador: 70, tiro_jugador: 75, pase_jugador: 77, talento_jugador: 80, defensa_jugador: 67, sueldo_jugador: 10000000
Presupuesto_anual: 2000000, entrenador: Juan, presidente: Adri, cantidad_jugadores: 8, nombre_jugador: Oscar, apellido_jugador: Boada, posicion_jugador: DELANTERO, tipo_jugador: DRAFT, velocidad_jugador: 72, fisico_jugador: 53, tiro_jugador: 80, pase_jugador: 63, talento_jugador: 79, defensa_jugador: 73, sueldo_jugador: 10000000
Presupuesto_anual: 2000000, entrenador: Marc, presidente: Gerard, cantidad_jugadores: 10, nombre_jugador: Fernan, apellido_jugador: Golobart, posicion_jugador: DEFENSA, tipo_jugador: WILD-CARD, velocidad_jugador: 99, fisico_jugador: 99, tiro_jugador: 99, pase_jugador: 99, talento_jugador: 99, defensa_jugador: 99, sueldo_jugador: 15000000
Presupuesto_anual: 2000000, entrenador: Marc, presidente: Gerard, cantidad_jugadores: 10, nombre_jugador: Chio, apellido_jugador: Alsina, posicion_jugador: MEDIO, tipo_jugador: DRAFT, velocidad_jugador: 93, fisico_jugador: 74, tiro_jugador: 87, pase_jugador: 76, talento_jugador: 84, defensa_jugador: 73, sueldo_jugador: 10000000
Presupuesto_anual: 2000000, entrenador: Marc, presidente: Gerard, cantidad_jugadores: 10, nombre_jugador: Pol, apellido_jugador: Zapata, posicion_jugador: PORTERO, tipo_jugador: DRAFT, velocidad_jugador: 0, fisico_jugador: 0, tiro_jugador: 0, pase_jugador: 0, talento_jugador: 99, defensa_jugador: 99, sueldo_jugador: 10000000
Presupuesto_anual: 2000000, entrenador: Marc, presidente: Gerard, cantidad_jugadores: 10, nombre_jugador: Jay, apellido_jugador: Mengeli, posicion_jugador: DEFENSA, tipo_jugador: DRAFT, velocidad_jugador: 86, fisico_jugador: 82, tiro_jugador: 74, pase_jugador: 66, talento_jugador: 76, defensa_jugador: 77, sueldo_jugador: 10500000
Presupuesto_anual: 2000000, entrenador: Marc, presidente: Gerard, cantidad_jugadores: 10, nombre_jugador: Salbano, apellido_jugador: Quero, posicion_jugador: MEDIO, tipo_jugador: DRAFT, velocidad_jugador: 83, fisico_jugador: 67, tiro_jugador: 73, pase_jugador: 86, talento_jugador: 83, defensa_jugador: 74, sueldo_jugador: 22500000
Presupuesto_anual: 2000000, entrenador: Marc, presidente: Gerard, cantidad_jugadores: 10, nombre_jugador: Arnau, apellido_jugador: Martínez, posicion_jugador: DEFENSA, tipo_jugador: DRAFT, velocidad_jugador: 74, fisico_jugador: 62, tiro_jugador: 81, pase_jugador: 60, talento_jugador: 68, defensa_jugador: 82, sueldo_jugador: 10500000
Presupuesto_anual: 2000000, entrenador: Marc, presidente: Gerard, cantidad_jugadores: 10, nombre_jugador: Iván, apellido_jugador: Pérez, posicion_jugador: DELANTERO, tipo_jugador: WILD-CARD, velocidad_jugador: 99, fisico_jugador: 99, tiro_jugador: 99, pase_jugador: 99, talento_jugador: 99, defensa_jugador: 99, sueldo_jugador: 22500000
Presupuesto_anual: 2000000, entrenador: Marc, presidente: Gerard, cantidad_jugadores: 10, nombre_jugador: Maca, apellido_jugador: Macarulla, posicion_jugador: MEDIO, tipo_jugador: DRAFT, velocidad_jugador: 72, fisico_jugador: 77, tiro_jugador: 72, pase_jugador: 72, talento_jugador: 87, defensa_jugador: 75, sueldo_jugador: 15000000
Presupuesto_anual: 2000000, entrenador: Marc, presidente: Gerard, cantidad_jugadores: 10, nombre_jugador: Noel, apellido_jugador: Bayarri, posicion_jugador: DEFENSA, tipo_jugador: DRAFT, velocidad_jugador: 72, fisico_jugador: 62, tiro_jugador: 71, pase_jugador: 64, talento_jugador: 72, defensa_jugador: 68, sueldo_jugador: 10000000
Presupuesto_anual: 2000000, entrenador: Marc, presidente: Gerard, cantidad_jugadores: 10, nombre_jugador: Pele, apellido_jugador: Dorado, posicion_jugador: DELANTERO, tipo_jugador: DRAFT, velocidad_jugador: 72, fisico_jugador: 52, tiro_jugador: 80, pase_jugador: 71, talento_jugador: 78, defensa_jugador: 58, sueldo_jugador: 10000000
Presupuesto_anual: 2000000, entrenador: Martín, presidente: Kun, cantidad_jugadores: 9, nombre_jugador: Carlos, apellido_jugador: Corominas, posicion_jugador: MEDIO, tipo_jugador: WILD-CARD, velocidad_jugador: 99, fisico_jugador: 99, tiro_jugador: 99, pase_jugador: 99, talento_jugador: 99, defensa_jugador: 99, sueldo_jugador: 22500000
Presupuesto_anual: 2000000, entrenador: Martín, presidente: Kun, cantidad_jugadores: 9, nombre_jugador: Torrente, apellido_jugador: Torrentbó, posicion_jugador: DELANTERO, tipo_jugador: DRAFT, velocidad_jugador: 73, fisico_jugador: 59, tiro_jugador: 73, pase_jugador: 76, talento_jugador: 75, defensa_jugador: 72, sueldo_jugador: 10500000
Presupuesto_anual: 2000000, entrenador: Martín, presidente: Kun, cantidad_jugadores: 9, nombre_jugador: Bernard, apellido_jugador: Guerrero, posicion_jugador: DEFENSA, tipo_jugador: DRAFT, velocidad_jugador: 71, fisico_jugador: 55, tiro_jugador: 82, pase_jugador: 77, talento_jugador: 83, defensa_jugador: 83, sueldo_jugador: 22500000
Presupuesto_anual: 2000000, entrenador: Martín, presidente: Kun, cantidad_jugadores: 9, nombre_jugador: Joan, apellido_jugador: Inés, posicion_jugador: MEDIO, tipo_jugador: DRAFT, velocidad_jugador: 72, fisico_jugador: 60, tiro_jugador: 78, pase_jugador: 64, talento_jugador: 64, defensa_jugador: 63, sueldo_jugador: 15000000
Presupuesto_anual: 2000000, entrenador: Martín, presidente: Kun, cantidad_jugadores: 9, nombre_jugador: Rode, apellido_jugador: Ródenas, posicion_jugador: PORTERO, tipo_jugador: DRAFT, velocidad_jugador: 0, fisico_jugador: 0, tiro_jugador: 0, pase_jugador: 0, talento_jugador: 99, defensa_jugador: 99, sueldo_jugador: 10000000
Presupuesto_anual: 2000000, entrenador: Martín, presidente: Kun, cantidad_jugadores: 9, nombre_jugador: Rode, apellido_jugador: Ródenas, posicion_jugador: PORTERO, tipo_jugador: DRAFT, velocidad_jugador: 0, fisico_jugador: 0, tiro_jugador: 0, pase_jugador: 0, talento_jugador: 99, defensa_jugador: 99, sueldo_jugador: 10000000
Presupuesto_anual: 2000000, entrenador: Martín, presidente: Kun, cantidad_jugadores: 9, nombre_jugador: Antonio, apellido_jugador: Ruggeri, posicion_jugador: DEFENSA, tipo_jugador: DRAFT, velocidad_jugador: 70, fisico_jugador: 56, tiro_jugador: 68, pase_jugador: 68, talento_jugador: 81, defensa_jugador: 85, sueldo_jugador: 10000000
Presupuesto_anual: 2000000, entrenador: Martín, presidente: Kun, cantidad_jugadores: 9, nombre_jugador: Manu, apellido_jugador: Hidalgo, posicion_jugador: DELANTERO, tipo_jugador: DRAFT, velocidad_jugador: 72, fisico_jugador: 56, tiro_jugador: 71, pase_jugador: 65, talento_jugador: 68, defensa_jugador: 74, sueldo_jugador: 10000000
Presupuesto_anual: 2000000, entrenador: Martín, presidente: Kun, cantidad_jugadores: 9, nombre_jugador: Miki, apellido_jugador: Fernández, posicion_jugador: DEFENSA, tipo_jugador: DRAFT, velocidad_jugador: 70, fisico_jugador: 53, tiro_jugador: 86, pase_jugador: 58, talento_jugador: 55, defensa_jugador: 69, sueldo_jugador: 22500000
Presupuesto_anual: 2000000, entrenador: Pol, presidente: Jaume, cantidad_jugadores: 9, nombre_jugador: Carlos, apellido_jugador: Planas, posicion_jugador: DEFENSA, tipo_jugador: WILD-CARD, velocidad_jugador: 99, fisico_jugador: 99, tiro_jugador: 99, pase_jugador: 99, talento_jugador: 99, defensa_jugador: 99, sueldo_jugador: 22500000
Presupuesto_anual: 2000000, entrenador: Pol, presidente: Jaume, cantidad_jugadores: 9, nombre_jugador: Ernan, apellido_jugador: Álvaro, posicion_jugador: DELANTERO, tipo_jugador: DRAFT, velocidad_jugador: 73, fisico_jugador: 82, tiro_jugador: 81, pase_jugador: 55, talento_jugador: 85, defensa_jugador: 70, sueldo_jugador: 22500000
Presupuesto_anual: 2000000, entrenador: Pol, presidente: Jaume, cantidad_jugadores: 9, nombre_jugador: Daniel, apellido_jugador: Soriano, posicion_jugador: DEFENSA, tipo_jugador: DRAFT, velocidad_jugador: 71, fisico_jugador: 70, tiro_jugador: 80, pase_jugador: 78, talento_jugador: 56, defensa_jugador: 57, sueldo_jugador: 10000000
Presupuesto_anual: 2000000, entrenador: Pol, presidente: Jaume, cantidad_jugadores: 9, nombre_jugador: Sergio, apellido_jugador: Sánchez, posicion_jugador: MEDIO, tipo_jugador: DRAFT, velocidad_jugador: 65, fisico_jugador: 43, tiro_jugador: 75, pase_jugador: 79, talento_jugador: 82, defensa_jugador: 84, sueldo_jugador: 10000000
Presupuesto_anual: 2000000, entrenador: Nacho, presidente: Mario, cantidad_jugadores: 9, nombre_jugador: Lucca, apellido_jugador: Ribeiro, posicion_jugador: MEDIO, tipo_jugador: DRAFT, velocidad_jugador: 72, fisico_jugador: 77, tiro_jugador: 77, pase_jugador: 50, talento_jugador: 77, defensa_jugador: 83, sueldo_jugador: 10500000
Presupuesto_anual: 2000000, entrenador: Victor, presidente: Javier, cantidad_jugadores: 9, nombre_jugador: Carlo, apellido_jugador: Castro, posicion_jugador: DELANTERO, tipo_jugador: WILD-CARD, velocidad_jugador: 99, fisico_jugador: 99, tiro_jugador: 99, pase_jugador: 99, talento_jugador: 99, defensa_jugador: 99, sueldo_jugador: 22500000
Presupuesto_anual: 2000000, entrenador: Victor, presidente: Javier, cantidad_jugadores: 9, nombre_jugador: Capi, apellido_jugador: Gutiérrez, posicion_jugador: PORTERO, tipo_jugador: DRAFT, velocidad_jugador: 0, fisico_jugador: 0, tiro_jugador: 0, pase_jugador: 0, talento_jugador: 99, defensa_jugador: 99, sueldo_jugador: 15000000
Presupuesto_anual: 2000000, entrenador: Victor, presidente: Javier, cantidad_jugadores: 9, nombre_jugador: Sorran, apellido_jugador: Poch, posicion_jugador: DELANTERO, tipo_jugador: DRAFT, velocidad_jugador: 68, fisico_jugador: 53, tiro_jugador: 84, pase_jugador: 79, talento_jugador: 79, defensa_jugador: 73, sueldo_jugador: 15000000
Presupuesto_anual: 2000000, entrenador: Victor, presidente: Javier, cantidad_jugadores: 9, nombre_jugador: Iñaki, apellido_jugador: Villalba, posicion_jugador: MEDIO, tipo_jugador: DRAFT, velocidad_jugador: 73, fisico_jugador: 64, tiro_jugador: 79, pase_jugador: 75, talento_jugador: 70, defensa_jugador: 70, sueldo_jugador: 15000000
Presupuesto_anual: 2000000, entrenador: Victor, presidente: Javier, cantidad_jugadores: 9, nombre_jugador: Dani, apellido_jugador: Santiago, posicion_jugador: DEFENSA, tipo_jugador: DRAFT, velocidad_jugador: 64, fisico_jugador: 69, tiro_jugador: 79, pase_jugador: 55, talento_jugador: 75, defensa_jugador: 83, sueldo_jugador: 10000000
Presupuesto_anual: 2000000, entrenador: Victor, presidente: Javier, cantidad_jugadores: 9, nombre_jugador: Goran, apellido_jugador: Ehsan, posicion_jugador: MEDIO, tipo_jugador: DRAFT, velocidad_jugador: 92, fisico_jugador: 61, tiro_jugador: 72, pase_jugador: 51, talento_jugador: 71, defensa_jugador: 60, sueldo_jugador: 15000000
Presupuesto_anual: 2000000, entrenador: Victor, presidente: Javier, cantidad_jugadores: 9, nombre_jugador: David, apellido_jugador: Bañuls, posicion_jugador: DEFENSA, tipo_jugador: DRAFT, velocidad_jugador: 71, fisico_jugador: 58, tiro_jugador: 81, pase_jugador: 76, talento_jugador: 76, defensa_jugador: 80, sueldo_jugador: 10000000
Presupuesto_anual: 2000000, entrenador: Victor, presidente: Javier, cantidad_jugadores: 9, nombre_jugador: Franc, apellido_jugador: Cortés, posicion_jugador: MEDIO, tipo_jugador: DRAFT, velocidad_jugador: 64, fisico_jugador: 46, tiro_jugador: 77, pase_jugador: 87, talento_jugador: 81, defensa_jugador: 74, sueldo_jugador: 22500000
Presupuesto_anual: 2000000, entrenador: Victor, presidente: Javier, cantidad_jugadores: 9, nombre_jugador: Berria, apellido_jugador: Sierra, posicion_jugador: DELANTERO, tipo_jugador: DRAFT, velocidad_jugador: 73, fisico_jugador: 66, tiro_jugador: 66, pase_jugador: 77, talento_jugador: 77, defensa_jugador: 75, sueldo_jugador: 15000000
Presupuesto_anual: 2000000, entrenador: Pol, presidente: Jaume, cantidad_jugadores: 9, nombre_jugador: Xavier, apellido_jugador: Molas, posicion_jugador: MEDIO, tipo_jugador: DRAFT, velocidad_jugador: 73, fisico_jugador: 72, tiro_jugador: 76, pase_jugador: 84, talento_jugador: 81, defensa_jugador: 78, sueldo_jugador: 10000000
Presupuesto_anual: 2000000, entrenador: Pol, presidente: Jaume, cantidad_jugadores: 9, nombre_jugador: Rodri, apellido_jugador: Martínez, posicion_jugador: DELANTERO, tipo_jugador: DRAFT, velocidad_jugador: 73, fisico_jugador: 50, tiro_jugador: 70, pase_jugador: 76, talento_jugador: 84, defensa_jugador: 73, sueldo_jugador: 10500000
Presupuesto_anual: 2000000, entrenador: Pol, presidente: Jaume, cantidad_jugadores: 9, nombre_jugador: Dorkis, apellido_jugador: Pérez, posicion_jugador: DELANTERO, tipo_jugador: DRAFT, velocidad_jugador: 72, fisico_jugador: 54, tiro_jugador: 78, pase_jugador: 54, talento_jugador: 71, defensa_jugador: 72, sueldo_jugador: 22500000
Presupuesto_anual: 2000000, entrenador: Pol, presidente: Jaume, cantidad_jugadores: 9, nombre_jugador: Manuel, apellido_jugador: Arús, posicion_jugador: PORTERO, tipo_jugador: DRAFT, velocidad_jugador: 0, fisico_jugador: 0, tiro_jugador: 0, pase_jugador: 0, talento_jugador: 99, defensa_jugador: 99, sueldo_jugador: 22500000
Presupuesto_anual: 2000000, entrenador: Pol, presidente: Jaume, cantidad_jugadores: 9, nombre_jugador: Manuel, apellido_jugador: Arús, posicion_jugador: PORTERO, tipo_jugador: DRAFT, velocidad_jugador: 0, fisico_jugador: 0, tiro_jugador: 0, pase_jugador: 0, talento_jugador: 99, defensa_jugador: 99, sueldo_jugador: 22500000
Presupuesto_anual: 2000000, entrenador: Gerardo, presidente: Samy, cantidad_jugadores: 10, nombre_jugador: Ferran, apellido_jugador: Lopo, posicion_jugador: DEFENSA, tipo_jugador: WILD-CARD, velocidad_jugador: 99, fisico_jugador: 99, tiro_jugador: 99, pase_jugador: 99, talento_jugador: 99, defensa_jugador: 99, sueldo_jugador: 10500000
Presupuesto_anual: 2000000, entrenador: Gerardo, presidente: Samy, cantidad_jugadores: 10, nombre_jugador: Jorge, apellido_jugador: Ibáñez, posicion_jugador: PORTERO, tipo_jugador: DRAFT, velocidad_jugador: 0, fisico_jugador: 0, tiro_jugador: 0, pase_jugador: 0, talento_jugador: 99, defensa_jugador: 99, sueldo_jugador: 15000000
Presupuesto_anual: 2000000, entrenador: Gerardo, presidente: Samy, cantidad_jugadores: 10, nombre_jugador: Carlitos, apellido_jugador: Val, posicion_jugador: DEFENSA, tipo_jugador: DRAFT, velocidad_jugador: 73, fisico_jugador: 64, tiro_jugador: 77, pase_jugador: 71, talento_jugador: 81, defensa_jugador: 85, sueldo_jugador: 10500000
Presupuesto_anual: 2000000, entrenador: Gerardo, presidente: Samy, cantidad_jugadores: 10, nombre_jugador: Pau, apellido_jugador: Fernández, posicion_jugador: MEDIO, tipo_jugador: DRAFT, velocidad_jugador: 71, fisico_jugador: 62, tiro_jugador: 71, pase_jugador: 82, talento_jugador: 75, defensa_jugador: 82, sueldo_jugador: 10500000
Presupuesto_anual: 2000000, entrenador: Gerardo, presidente: Samy, cantidad_jugadores: 10, nombre_jugador: Ignacio, apellido_jugador: Cabello, posicion_jugador: DELANTERO, tipo_jugador: WILD-CARD, velocidad_jugador: 99, fisico_jugador: 99, tiro_jugador: 99, pase_jugador: 99, talento_jugador: 99, defensa_jugador: 99, sueldo_jugador: 22500000
Presupuesto_anual: 2000000, entrenador: Gerardo, presidente: Samy, cantidad_jugadores: 10, nombre_jugador: Beñat, apellido_jugador: Juárez, posicion_jugador: MEDIO, tipo_jugador: DRAFT, velocidad_jugador: 71, fisico_jugador: 65, tiro_jugador: 75, pase_jugador: 55, talento_jugador: 71, defensa_jugador: 77, sueldo_jugador: 22500000
Presupuesto_anual: 2000000, entrenador: Gerardo, presidente: Samy, cantidad_jugadores: 10, nombre_jugador: Alexis, apellido_jugador: Turner, posicion_jugador: DEFENSA, tipo_jugador: DRAFT, velocidad_jugador: 73, fisico_jugador: 59, tiro_jugador: 72, pase_jugador: 77, talento_jugador: 80, defensa_jugador: 80, sueldo_jugador: 10000000
Presupuesto_anual: 2000000, entrenador: Gerardo, presidente: Samy, cantidad_jugadores: 10, nombre_jugador: Adri, apellido_jugador: Castro, posicion_jugador: DELANTERO, tipo_jugador: DRAFT, velocidad_jugador: 70, fisico_jugador: 45, tiro_jugador: 80, pase_jugador: 89, talento_jugador: 82, defensa_jugador: 81, sueldo_jugador: 22500000
Presupuesto_anual: 2000000, entrenador: Gerardo, presidente: Samy, cantidad_jugadores: 10, nombre_jugador: Cokita, apellido_jugador: López, posicion_jugador: MEDIO, tipo_jugador: DRAFT, velocidad_jugador: 67, fisico_jugador: 47, tiro_jugador: 79, pase_jugador: 75, talento_jugador: 80, defensa_jugador: 71, sueldo_jugador: 10000000
Presupuesto_anual: 2000000, entrenador: Gerardo, presidente: Samy, cantidad_jugadores: 10, nombre_jugador: Unai, apellido_jugador: Santiago, posicion_jugador: DEFENSA, tipo_jugador: DRAFT, velocidad_jugador: 67, fisico_jugador: 46, tiro_jugador: 71, pase_jugador: 74, talento_jugador: 78, defensa_jugador: 70, sueldo_jugador: 10000000
Presupuesto_anual: 2000000, entrenador: Juvenal, presidente: Ibai, cantidad_jugadores: 10, nombre_jugador: Martin, apellido_jugador: Espinosa, posicion_jugador: MEDIO, tipo_jugador: WILD-CARD, velocidad_jugador: 99, fisico_jugador: 99, tiro_jugador: 99, pase_jugador: 99, talento_jugador: 99, defensa_jugador: 99, sueldo_jugador: 22500000
Presupuesto_anual: 2000000, entrenador: Juvenal, presidente: Ibai, cantidad_jugadores: 10, nombre_jugador: Jorge, apellido_jugador: Segovia, posicion_jugador: PORTERO, tipo_jugador: DRAFT, velocidad_jugador: 0, fisico_jugador: 0, tiro_jugador: 0, pase_jugador: 0, talento_jugador: 99, defensa_jugador: 99, sueldo_jugador: 15000000
Presupuesto_anual: 2000000, entrenador: Juvenal, presidente: Ibai, cantidad_jugadores: 10, nombre_jugador: Guillermo, apellido_jugador: Cichero, posicion_jugador: DEFENSA, tipo_jugador: DRAFT, velocidad_jugador: 73, fisico_jugador: 49, tiro_jugador: 66, pase_jugador: 75, talento_jugador: 76, defensa_jugador: 74, sueldo_jugador: 22500000
Presupuesto_anual: 2000000, entrenador: Juvenal, presidente: Ibai, cantidad_jugadores: 10, nombre_jugador: David, apellido_jugador: López, posicion_jugador: DEFENSA, tipo_jugador: DRAFT, velocidad_jugador: 70, fisico_jugador: 48, tiro_jugador: 80, pase_jugador: 62, talento_jugador: 81, defensa_jugador: 75, sueldo_jugador: 10000000
Presupuesto_anual: 2000000, entrenador: Juvenal, presidente: Ibai, cantidad_jugadores: 10, nombre_jugador: Toti, apellido_jugador: Sàlvia, posicion_jugador: MEDIO, tipo_jugador: DRAFT, velocidad_jugador: 72, fisico_jugador: 58, tiro_jugador: 80, pase_jugador: 69, talento_jugador: 78, defensa_jugador: 73, sueldo_jugador: 10000000
Presupuesto_anual: 2000000, entrenador: Juvenal, presidente: Ibai, cantidad_jugadores: 10, nombre_jugador: Carlitos, apellido_jugador: González, posicion_jugador: MEDIO, tipo_jugador: WILD-CARD, velocidad_jugador: 99, fisico_jugador: 99, tiro_jugador: 99, pase_jugador: 99, talento_jugador: 99, defensa_jugador: 99, sueldo_jugador: 15000000
Presupuesto_anual: 2000000, entrenador: Juvenal, presidente: Ibai, cantidad_jugadores: 10, nombre_jugador: Killian, apellido_jugador: Honorato, posicion_jugador: DELANTERO, tipo_jugador: DRAFT, velocidad_jugador: 72, fisico_jugador: 70, tiro_jugador: 87, pase_jugador: 69, talento_jugador: 78, defensa_jugador: 73, sueldo_jugador: 15000000
Presupuesto_anual: 2000000, entrenador: Juvenal, presidente: Ibai, cantidad_jugadores: 10, nombre_jugador: Juan, apellido_jugador: Blanco, posicion_jugador: DELANTERO, tipo_jugador: DRAFT, velocidad_jugador: 73, fisico_jugador: 54, tiro_jugador: 65, pase_jugador: 66, talento_jugador: 71, defensa_jugador: 65, sueldo_jugador: 15000000
Presupuesto_anual: 2000000, entrenador: Juvenal, presidente: Ibai, cantidad_jugadores: 10, nombre_jugador: Hernesto, apellido_jugador: Lao, posicion_jugador: MEDIO, tipo_jugador: DRAFT, velocidad_jugador: 73, fisico_jugador: 69, tiro_jugador: 89, pase_jugador: 65, talento_jugador: 74, defensa_jugador: 77, sueldo_jugador: 22500000
Presupuesto_anual: 2000000, entrenador: Juan, presidente: Marti, cantidad_jugadores: 9, nombre_jugador: Poloteli, apellido_jugador: Marcó, posicion_jugador: DEFENSA, tipo_jugador: WILD-CARD, velocidad_jugador: 99, fisico_jugador: 99, tiro_jugador: 99, pase_jugador: 99, talento_jugador: 99, defensa_jugador: 99, sueldo_jugador: 10000000
Presupuesto_anual: 2000000, entrenador: Juan, presidente: Marti, cantidad_jugadores: 9, nombre_jugador: Mikel, apellido_jugador: Canet, posicion_jugador: PORTERO, tipo_jugador: DRAFT, velocidad_jugador: 0, fisico_jugador: 0, tiro_jugador: 0, pase_jugador: 0, talento_jugador: 99, defensa_jugador: 99, sueldo_jugador: 15000000
Presupuesto_anual: 2000000, entrenador: Juan, presidente: Marti, cantidad_jugadores: 9, nombre_jugador: Guillem, apellido_jugador: Ruiz, posicion_jugador: DELANTERO, tipo_jugador: DRAFT, velocidad_jugador: 69, fisico_jugador: 52, tiro_jugador: 84, pase_jugador: 63, talento_jugador: 81, defensa_jugador: 80, sueldo_jugador: 10000000
Presupuesto_anual: 2000000, entrenador: Juan, presidente: Marti, cantidad_jugadores: 9, nombre_jugador: Mariano, apellido_jugador: Reyes, posicion_jugador: DEFENSA, tipo_jugador: DRAFT, velocidad_jugador: 66, fisico_jugador: 53, tiro_jugador: 76, pase_jugador: 72, talento_jugador: 73, defensa_jugador: 69, sueldo_jugador: 15000000
Presupuesto_anual: 2000000, entrenador: Juan, presidente: Marti, cantidad_jugadores: 9, nombre_jugador: Franky, apellido_jugador: Purtí, posicion_jugador: MEDIO, tipo_jugador: DRAFT, velocidad_jugador: 73, fisico_jugador: 71, tiro_jugador: 74, pase_jugador: 66, talento_jugador: 82, defensa_jugador: 78, sueldo_jugador: 15000000
Presupuesto_anual: 2000000, entrenador: Juan, presidente: Marti, cantidad_jugadores: 9, nombre_jugador: Dani , apellido_jugador: Pérez, posicion_jugador: MEDIO, tipo_jugador: DRAFT, velocidad_jugador: 96, fisico_jugador: 75, tiro_jugador: 78, pase_jugador: 88, talento_jugador: 66, defensa_jugador: 62, sueldo_jugador: 10000000
Presupuesto_anual: 2000000, entrenador: Juan, presidente: Marti, cantidad_jugadores: 9, nombre_jugador: Alejandro, apellido_jugador: García, posicion_jugador: DEFENSA, tipo_jugador: DRAFT, velocidad_jugador: 72, fisico_jugador: 51, tiro_jugador: 57, pase_jugador: 70, talento_jugador: 68, defensa_jugador: 74, sueldo_jugador: 10500000
Presupuesto_anual: 2000000, entrenador: Juan, presidente: Marti, cantidad_jugadores: 9, nombre_jugador: Anton, apellido_jugador: Biboum, posicion_jugador: DELANTERO, tipo_jugador: DRAFT, velocidad_jugador: 72, fisico_jugador: 58, tiro_jugador: 80, pase_jugador: 88, talento_jugador: 68, defensa_jugador: 70, sueldo_jugador: 15000000
Presupuesto_anual: 2000000, entrenador: Juan, presidente: Marti, cantidad_jugadores: 9, nombre_jugador: Jonathan, apellido_jugador: Jiménez, posicion_jugador: MEDIO, tipo_jugador: DRAFT, velocidad_jugador: 85, fisico_jugador: 73, tiro_jugador: 80, pase_jugador: 60, talento_jugador: 62, defensa_jugador: 62, sueldo_jugador: 15000000
Presupuesto_anual: 2000000, entrenador: Daniel, presidente: David, cantidad_jugadores: 9, nombre_jugador: David, apellido_jugador: López, posicion_jugador: MEDIO, tipo_jugador: WILD-CARD, velocidad_jugador: 99, fisico_jugador: 99, tiro_jugador: 99, pase_jugador: 99, talento_jugador: 99, defensa_jugador: 99, sueldo_jugador: 10000000
Presupuesto_anual: 2000000, entrenador: Daniel, presidente: David, cantidad_jugadores: 9, nombre_jugador: Pedro, apellido_jugador: Briones, posicion_jugador: PORTERO, tipo_jugador: DRAFT, velocidad_jugador: 0, fisico_jugador: 0, tiro_jugador: 0, pase_jugador: 0, talento_jugador: 99, defensa_jugador: 99, sueldo_jugador: 10500000
Presupuesto_anual: 2000000, entrenador: Daniel, presidente: David, cantidad_jugadores: 9, nombre_jugador: Gio, apellido_jugador: Ferinu, posicion_jugador: DELANTERO, tipo_jugador: DRAFT, velocidad_jugador: 71, fisico_jugador: 67, tiro_jugador: 74, pase_jugador: 75, talento_jugador: 85, defensa_jugador: 77, sueldo_jugador: 22500000
Presupuesto_anual: 2000000, entrenador: Daniel, presidente: David, cantidad_jugadores: 9, nombre_jugador: Campu, apellido_jugador: Campuzano, posicion_jugador: DEFENSA, tipo_jugador: DRAFT, velocidad_jugador: 70, fisico_jugador: 53, tiro_jugador: 80, pase_jugador: 78, talento_jugador: 78, defensa_jugador: 83, sueldo_jugador: 22500000
Presupuesto_anual: 2000000, entrenador: Daniel, presidente: David, cantidad_jugadores: 9, nombre_jugador: Canales, apellido_jugador: Valle, posicion_jugador: MEDIO, tipo_jugador: DRAFT, velocidad_jugador: 71, fisico_jugador: 52, tiro_jugador: 76, pase_jugador: 86, talento_jugador: 78, defensa_jugador: 66, sueldo_jugador: 15000000
Presupuesto_anual: 2000000, entrenador: Daniel, presidente: David, cantidad_jugadores: 9, nombre_jugador: Victor, apellido_jugador: Torres, posicion_jugador: DEFENSA, tipo_jugador: DRAFT, velocidad_jugador: 71, fisico_jugador: 39, tiro_jugador: 74, pase_jugador: 73, talento_jugador: 69, defensa_jugador: 60, sueldo_jugador: 15000000
Presupuesto_anual: 2000000, entrenador: Daniel, presidente: David, cantidad_jugadores: 9, nombre_jugador: Feliu, apellido_jugador: Torrus, posicion_jugador: MEDIO, tipo_jugador: DRAFT, velocidad_jugador: 72, fisico_jugador: 64, tiro_jugador: 83, pase_jugador: 60, talento_jugador: 82, defensa_jugador: 84, sueldo_jugador: 10000000
Presupuesto_anual: 2000000, entrenador: Daniel, presidente: David, cantidad_jugadores: 9, nombre_jugador: David, apellido_jugador: Alba, posicion_jugador: DELANTERO, tipo_jugador: DRAFT, velocidad_jugador: 75, fisico_jugador: 75, tiro_jugador: 80, pase_jugador: 65, talento_jugador: 73, defensa_jugador: 64, sueldo_jugador: 22500000
Presupuesto_anual: 2000000, entrenador: Daniel, presidente: David, cantidad_jugadores: 9, nombre_jugador: Ramon, apellido_jugador: Carbó, posicion_jugador: MEDIO, tipo_jugador: DRAFT, velocidad_jugador: 71, fisico_jugador: 49, tiro_jugador: 63, pase_jugador: 67, talento_jugador: 66, defensa_jugador: 62, sueldo_jugador: 22500000
Presupuesto_anual: 2000000, entrenador: Nacho, presidente: Mario, cantidad_jugadores: 9, nombre_jugador: Juanma, apellido_jugador: González, posicion_jugador: MEDIO, tipo_jugador: WILD-CARD, velocidad_jugador: 99, fisico_jugador: 99, tiro_jugador: 99, pase_jugador: 99, talento_jugador: 99, defensa_jugador: 99, sueldo_jugador: 22500000
Presupuesto_anual: 2000000, entrenador: Nacho, presidente: Mario, cantidad_jugadores: 9, nombre_jugador: Arché, apellido_jugador: García, posicion_jugador: MEDIO, tipo_jugador: DRAFT, velocidad_jugador: 72, fisico_jugador: 69, tiro_jugador: 79, pase_jugador: 78, talento_jugador: 77, defensa_jugador: 65, sueldo_jugador: 15000000
Presupuesto_anual: 2000000, entrenador: Nacho, presidente: Mario, cantidad_jugadores: 9, nombre_jugador: Thomas, apellido_jugador: Morral, posicion_jugador: PORTERO, tipo_jugador: DRAFT, velocidad_jugador: 0, fisico_jugador: 0, tiro_jugador: 0, pase_jugador: 0, talento_jugador: 99, defensa_jugador: 99, sueldo_jugador: 22500000
Presupuesto_anual: 2000000, entrenador: Nacho, presidente: Mario, cantidad_jugadores: 9, nombre_jugador: Guti, apellido_jugador: Gutiérrez, posicion_jugador: DEFENSA, tipo_jugador: DRAFT, velocidad_jugador: 73, fisico_jugador: 62, tiro_jugador: 76, pase_jugador: 58, talento_jugador: 74, defensa_jugador: 77, sueldo_jugador: 22500000
Presupuesto_anual: 2000000, entrenador: Nacho, presidente: Mario, cantidad_jugadores: 9, nombre_jugador: Aleix, apellido_jugador: Lage, posicion_jugador: MEDIO, tipo_jugador: DRAFT, velocidad_jugador: 87, fisico_jugador: 64, tiro_jugador: 65, pase_jugador: 72, talento_jugador: 74, defensa_jugador: 70, sueldo_jugador: 22500000
Presupuesto_anual: 2000000, entrenador: Nacho, presidente: Mario, cantidad_jugadores: 9, nombre_jugador: Llur, apellido_jugador: Genesca, posicion_jugador: DELANTERO, tipo_jugador: DRAFT, velocidad_jugador: 71, fisico_jugador: 53, tiro_jugador: 75, pase_jugador: 59, talento_jugador: 66, defensa_jugador: 67, sueldo_jugador: 10500000
Presupuesto_anual: 2000000, entrenador: Juvenal, presidente: Ibai, cantidad_jugadores: 10, nombre_jugador: Iker, apellido_jugador: López, posicion_jugador: DEFENSA, tipo_jugador: DRAFT, velocidad_jugador: 73, fisico_jugador: 67, tiro_jugador: 79, pase_jugador: 84, talento_jugador: 69, defensa_jugador: 71, sueldo_jugador: 15000000
Presupuesto_anual: 2000000, entrenador: Nacho, presidente: Mario, cantidad_jugadores: 9, nombre_jugador: Ian, apellido_jugador: González, posicion_jugador: DEFENSA, tipo_jugador: DRAFT, velocidad_jugador: 87, fisico_jugador: 54, tiro_jugador: 64, pase_jugador: 54, talento_jugador: 74, defensa_jugador: 76, sueldo_jugador: 15000000
Presupuesto_anual: 2000000, entrenador: Nacho, presidente: Mario, cantidad_jugadores: 9, nombre_jugador: Zea, apellido_jugador: Rodríguez, posicion_jugador: DELANTERO, tipo_jugador: DRAFT, velocidad_jugador: 72, fisico_jugador: 49, tiro_jugador: 72, pase_jugador: 53, talento_jugador: 75, defensa_jugador: 79, sueldo_jugador: 15000000

Procedimiento PL/SQL terminado correctamente.

Procedimiento PL/SQL terminado correctamente.

*/