BEGIN
    GESTION_CALENDARIO.CREAR_SPLIT('VERANO');
    GESTION_CALENDARIO.GENERAR_ENFRENTAMIENTOS;
END;
SELECT * FROM EMPAREJAMIENTOS;
SELECT * FROM SPLIT;
SELECT * FROM JORNADAS; -- HAY 11 JORNDAS NORMALES POR SPLIT
SELECT * FROM PARTIDOS;
SELECT COUNT(*) "ENFRENTAMIENTOS REPETIDOS" FROM PARTIDOS P1
WHERE EXISTS(
 SELECT 'X' FROM PARTIDOS P2 
    WHERE ((P1.ID_EQUIPO1 = P2.ID_EQUIPO1 AND P1.ID_EQUIPO2 = P2.ID_EQUIPO2)
    OR (P1.ID_EQUIPO1 = P2.ID_EQUIPO2 AND P1.ID_EQUIPO2 = P2.ID_EQUIPO1)) AND P1.ID_JORNADA != P2.ID_JORNADA);

SELECT COUNT(*) FROM PARTIDOS GROUP BY ID_JORNADA; -- EN LAS 11 HAY 6

SELECT * FROM EQUIPOS;

SELECT * FROM PARTIDOS_HISTORIAL;


