CREATE OR REPLACE VIEW V_INFO_EQUIPOS AS  
SELECT 
    E.*,
    (SELECT NOMBRE FROM PERSONALES P, CONTRATOS_PERSONAL CP 
    WHERE P.ID = CP.ID_PERSONAL AND UPPER(P.OFICIO) = 'ENTRENADOR' AND E.ID = CP.ID_EQUIPO) ENTRENADOR,
    (SELECT NOMBRE FROM PERSONALES P, CONTRATOS_PERSONAL CP 
    WHERE P.ID = CP.ID_PERSONAL AND UPPER(P.OFICIO) = 'PRESIDENTE' AND E.ID = CP.ID_EQUIPO) PRESIDENTE,
    (SELECT COUNT(*) FROM JUGADORES J, CONTRATOS_JUGADORES CJ 
    WHERE J.ID =  CJ.ID_EQUIPO AND E.ID = CJ.ID_EQUIPO) CANTIDAD_JUGADORES,
    J.*,
    CJ.SUELDO
FROM EQUIPOS E, CONTRATOS_JUGADORES CJ, JUGADORES J
WHERE E.ID = CJ.ID_EQUIPO AND CJ.ID_JUGADOR = J.ID;

SELECT * FROM V_INFO_EQUIPOS;