CREATE OR REPLACE VIEW CLASIFICACION AS
SELECT 
    ROW_NUMBER() over (order by COUNT(CASE WHEN P.ID_EQUIPO1 = E.ID AND P.GOLES_EQUIPO1 > P.GOLES_EQUIPO2 
               OR P.ID_EQUIPO2 = E.ID AND P.GOLES_EQUIPO2 > P.GOLES_EQUIPO1 THEN 1 END) desc, SUM(CASE WHEN E.ID = P.ID_EQUIPO1 THEN P.GOLES_EQUIPO1 - P.GOLES_EQUIPO2 ELSE P.GOLES_EQUIPO2 - P.GOLES_EQUIPO1 END) desc) POSICION,
    J.ID_SPLIT SPLIT,
    E.NOMBRE AS EQUIPO,
    COUNT(CASE WHEN P.ID_EQUIPO1 = E.ID AND P.GOLES_EQUIPO1 > P.GOLES_EQUIPO2 
               OR P.ID_EQUIPO2 = E.ID AND P.GOLES_EQUIPO2 > P.GOLES_EQUIPO1 THEN 1 END) AS VICTORIAS,
    SUM(CASE WHEN E.ID = P.ID_EQUIPO1 THEN P.GOLES_EQUIPO1 ELSE P.GOLES_EQUIPO2 END) AS GOLES_A_FAVOR,
    SUM(CASE WHEN E.ID = P.ID_EQUIPO1 THEN P.GOLES_EQUIPO2 ELSE P.GOLES_EQUIPO1 END) AS GOLES_EN_CONTRA,
    SUM(CASE WHEN E.ID = P.ID_EQUIPO1 THEN P.GOLES_EQUIPO1 - P.GOLES_EQUIPO2 ELSE P.GOLES_EQUIPO2 - P.GOLES_EQUIPO1 END) AS BALANCE_GOLES
FROM EQUIPOS E, PARTIDOS P, JORNADAS J
WHERE ((E.ID = P.ID_EQUIPO1 OR E.ID = P.ID_EQUIPO2 AND J.TIPO = 'NORMAL') AND P.ID_JORNADA = J.ID) AND J.ID = P.ID_JORNADA 
GROUP BY E.ID, E.NOMBRE, J.ID_SPLIT
ORDER BY VICTORIAS DESC, BALANCE_GOLES DESC, GOLES_A_FAVOR DESC;





SELECT * FROM PARTIDOS;

