CREATE OR REPLACE VIEW V_INFO_PARTIDOS_JORNADA AS  
SELECT
    S.TIPO TIPO_SPLIT,
    J.ID JORNADA,
    J.TIPO TIPO_JORNADA,
    P.*
    /*
    ,
    P.ID,
    P.GOLES_EQUIPO1,
    P.GOLES_EQUIPO2,
    P.FECHA,
    P.LUGAR,
    P.ID_JORNADA,
    P.ID_EQUIPO1,
    P.ID_EQUIPO2
    */
FROM SPLIT S, JORNADAS J, PARTIDOS P
WHERE S.ID=J.ID_SPLIT AND J.ID=P.ID_JORNADA;

SELECT * FROM V_INFO_PARTIDOS_JORNADA;