CREATE OR REPLACE VIEW V_INFO_EQUIPOS AS
SELECT
    E.*,
    P1.ID ID_ENTRENADOR,
    P2.ID ID_PRESIDENTE,
    (SELECT COUNT(*) FROM JUGADORES J, CONTRATOS_JUGADORES CJ
     WHERE J.ID =  CJ.ID_EQUIPO AND E.ID = CJ.ID_EQUIPO) CANTIDADJUGADORES,
    J.ID ID_JUGADOR,
    J.NOMBRE NOMBRE_JUGADOR,
    J.APELLIDOS,
    J.POSICION,
    J.TIPO,
    J.VELOCIDAD,
    J.FISICO,
    J.TIRO,
    J.PASE,
    J.TALENTO,
    J.DEFENSA,
    J.IMG,
    CJ.SUELDO
FROM EQUIPOS E, CONTRATOS_JUGADORES CJ, JUGADORES J, PERSONALES P1, PERSONALES P2, CONTRATOS_PERSONAL CP1, CONTRATOS_PERSONAL CP2
WHERE E.ID = CJ.ID_EQUIPO AND CJ.ID_JUGADOR = J.ID 
AND UPPER(P1.OFICIO) = 'ENTRENADOR' AND UPPER(P2.OFICIO) = 'PRESIDENTE'
AND CP1.ID_EQUIPO = E.ID AND CP1.ID_PERSONAL = P1.ID AND CP2.ID_EQUIPO = E.ID AND CP2.ID_PERSONAL = P2.ID;

SELECT * FROM V_INFO_EQUIPOS;
