CREATE OR REPLACE PACKAGE PAQUETE_XML AS
    PROCEDURE GENERAR_XML_JORNADAS;
    PROCEDURE GENERAR_XML_CLASIFICACION;
    PROCEDURE GENERAR_XML_ULTIMA_JORNADA(XML OUT CLOB);
END PAQUETE_XML;

select * from GENERAR_XML_JORNADAS;
desc GENERAR_XML_JORNADAS;