CREATE OR REPLACE TRIGGER MAX_NUM_PRESIDENTE
FOR INSERT OR UPDATE OF ID_EQUIPO ON CONTRATOS_PERSONAL
COMPOUND TRIGGER
NEWIDEQUIPO CONTRATOS_JUGADORES.ID_EQUIPO%TYPE:=NULL;
BEFORE EACH ROW IS
BEGIN
NEWIDEQUIPO:=:NEW.ID_EQUIPO;
END BEFORE EACH ROW;
AFTER STATEMENT IS
    V_NUM NUMBER:=0;
    MENSAJE VARCHAR2(100):=CONCAT ('SOLO PUEDE HABER UN PRESIDENTE EN EL EQUIPO', NEWIDEQUIPO);
BEGIN
SELECT COUNT(CJ.ID_PERSONAL) INTO V_NUM
    FROM CONTRATOS_PERSONAL CJ, PERSONALES P
    WHERE CJ.ID_EQUIPO = NEWIDEQUIPO AND P.OFICIO='PRESIDENTE';
    IF V_NUM > 1
        THEN 
        RAISE_APPLICATION_ERROR(-20001, MENSAJE);
    END IF;
    END AFTER STATEMENT;
END MAX_NUM_PRESIDENTE;
/*

select * from contratos_personal;

UPDATE PERSONALES SET OFICIO = 'PRESIDENTE' WHERE ID = 2;

Error que empieza en la línea: 1 del comando -
UPDATE CONTRATOS_PERSONAL SET ID_EQUIPO = 1 WHERE ID_PERSONAL = 13
Error en la línea de comandos : 1 Columna : 8
Informe de error -
Error SQL: ORA-20001: SOLO PUEDE HABER UN PRESIDENTE EN EL EQUIPO1
ORA-06512: en "SYSTEM.MAX_NUM_PRESIDENTE", línea 16
ORA-04088: error durante la ejecución del disparador 'SYSTEM.MAX_NUM_PRESIDENTE'
*/
