CREATE OR REPLACE TRIGGER MAX_NUM_JUGADORES
FOR INSERT OR UPDATE OF ID_EQUIPO ON CONTRATOS_JUGADORES
COMPOUND TRIGGER
NEWIDEQUIPO CONTRATOS_JUGADORES.ID_EQUIPO%TYPE:=NULL;
BEFORE EACH ROW IS
BEGIN
NEWIDEQUIPO:=:NEW.ID_EQUIPO;
END BEFORE EACH ROW;
AFTER STATEMENT IS
    V_NUM NUMBER:=0;
    MENSAJE VARCHAR2(100):=CONCAT ('DEMASIADOS JUGADORES EN EL EQUIPO ', NEWIDEQUIPO);
BEGIN
SELECT COUNT(*) INTO V_NUM
    FROM CONTRATOS_JUGADORES
    WHERE ID_EQUIPO = NEWIDEQUIPO;
    IF V_NUM > 10
        THEN 
        RAISE_APPLICATION_ERROR(-20001, MENSAJE);
    END IF;
    END AFTER STATEMENT;
END MAX_NUM_JUGADORES;
/*
UPDATE CONTRATOS_JUGADORES
SET ID_EQUIPO=1
WHERE ID_EQUIPO=2;
Error en la línea de comandos : 25 Columna : 8
Informe de error -
Error SQL: ORA-20001: DEMASIADOS JUGADORES EN EL EQUIPO 1
ORA-06512: en "SYSTEM.MAX_NUM_JUGADORES", línea 16
ORA-04088: error durante la ejecución del disparador 'SYSTEM.MAX_NUM_JUGADORES'
*/