CREATE OR REPLACE TRIGGER MAX_NUM_JUGADORES
FOR INSERT OR UPDATE OF ID_EQUIPO ON CONTRATOS_JUGADORES
COMPOUND TRIGGER
NEWIDEQUIPO CONTRATOS_JUGADORES.ID_EQUIPO%TYPE:=NULL;
BEFORE EACH ROW IS
BEGIN
NEWIDEQUIPO:=:NEW.ID_EQUIPO;
END BEFORE EACH ROW;
AFTER STATEMENT IS
    V_NUM NUMBER:=0;
    MENSAJE VARCHAR2(100):=CONCAT ('DEMASIADOS JUGADORES EN EL EQUIPO ', NEWIDEQUIPO);
BEGIN
SELECT COUNT(*) INTO V_NUM
    FROM CONTRATOS_JUGADORES
    WHERE ID_EQUIPO = NEWIDEQUIPO;
    IF V_NUM > 10
        THEN 
        RAISE_APPLICATION_ERROR(-20001, MENSAJE);
    END IF;
    END AFTER STATEMENT;
END MAX_NUM_JUGADORES;

DROP TRIGGER MAX_NUM_JUGADORES;