CREATE OR REPLACE TRIGGER TRG_NO_DUPLICATE_DORSAL
FOR INSERT OR UPDATE OF DORSAL ON CONTRATOS_JUGADORES
COMPOUND TRIGGER
  NEWIDEQUIPO CONTRATOS_JUGADORES.ID_EQUIPO%TYPE;
  NEWDORSAL CONTRATOS_JUGADORES.DORSAL%TYPE;
  BEFORE EACH ROW IS 
  BEGIN
        NEWIDEQUIPO:=:NEW.ID_EQUIPO;
        NEWDORSAL:=:NEW.DORSAL;
  END BEFORE EACH ROW;
  
  AFTER STATEMENT IS
  V_COUNT NUMBER:=0;
  BEGIN
    SELECT COUNT(*) INTO V_COUNT
    FROM CONTRATOS_JUGADORES
    WHERE ID_EQUIPO = NEWIDEQUIPO AND DORSAL =NEWDORSAL;

    IF V_COUNT > 0 THEN
      RAISE_APPLICATION_ERROR(-20001, 'No se puede agregar o actualizar el jugador porque ya existe otro jugador con el mismo dorsal en el mismo equipo.');
    END IF;
  END AFTER STATEMENT;
END;

SELECT * FROM CONTRATOS_JUGADORES WHERE ID_EQUIPO=12;

UPDATE CONTRATOS_JUGADORES SET DORSAL = 26 WHERE ID_JUGADOR = 40;