CREATE OR REPLACE TRIGGER JUGADORES_JORNADA_TRG
BEFORE INSERT OR UPDATE OR DELETE ON JUGADORES
FOR EACH ROW
DECLARE
V_SPLIT_ESTADO VARCHAR2(10);
V_ID_JORNADA NUMBER;
JORNADA_EXISTENTE EXCEPTION;
BEGIN
  SELECT ESTADO INTO V_SPLIT_ESTADO FROM SPLIT  WHERE ID IN (SELECT MAX(ID_SPLIT) FROM JORNADAS);
  IF V_SPLIT_ESTADO = 'CERRADO' THEN
    RAISE JORNADA_EXISTENTE;
    END IF;
EXCEPTION
  WHEN JORNADA_EXISTENTE THEN
    RAISE_APPLICATION_ERROR(-20001, 'No se puede realizar esta operación mientras hay una jornada en curso.');
    WHEN NO_DATA_FOUND THEN 
    NULL;
END;

/*
UPDATE JUGADORES
SET nombre='MANOLO' WHERE DNI='11111265A';

Error que empieza en la línea: 18 del comando -
UPDATE JUGADORES
SET nombre='MANOLO' WHERE DNI='11111265A';
Error en la línea de comandos : 18 Columna : 8
Informe de error -
Error SQL: ORA-20001: No se puede realizar esta operación mientras hay una jornada en curso.
ORA-06512: en "SYSTEM.JUGADORES_JORNADA_TRG", línea 12
ORA-04088: error durante la ejecución del disparador 'SYSTEM.JUGADORES_JORNADA_TRG'
*/