INSERT INTO EQUIPOS (NOMBRE, PRESUPUESTO_ANUAL) VALUES ('Saiyans FC', 2000000);
INSERT INTO EQUIPOS (NOMBRE, PRESUPUESTO_ANUAL) VALUES ('Ultimate Mostoles', 2000000);
INSERT INTO EQUIPOS (NOMBRE, PRESUPUESTO_ANUAL) VALUES ('El Barrio', 2000000);
INSERT INTO EQUIPOS (NOMBRE, PRESUPUESTO_ANUAL) VALUES ('Kunisports', 2000000);
INSERT INTO EQUIPOS (NOMBRE, PRESUPUESTO_ANUAL) VALUES ('PIO FC', 2000000);
INSERT INTO EQUIPOS (NOMBRE, PRESUPUESTO_ANUAL) VALUES ('Aniquiladores FC', 2000000);
INSERT INTO EQUIPOS (NOMBRE, PRESUPUESTO_ANUAL) VALUES ('Los Troncos FC', 2000000);
INSERT INTO EQUIPOS (NOMBRE, PRESUPUESTO_ANUAL) VALUES ('1K FC', 2000000);
INSERT INTO EQUIPOS (NOMBRE, PRESUPUESTO_ANUAL) VALUES ('Rayo de Barcelona', 2000000);
INSERT INTO EQUIPOS (NOMBRE, PRESUPUESTO_ANUAL) VALUES ('xBuyer Team', 2000000);
INSERT INTO EQUIPOS (NOMBRE, PRESUPUESTO_ANUAL) VALUES ('Porcinos FC', 2000000);
INSERT INTO EQUIPOS (NOMBRE, PRESUPUESTO_ANUAL)VALUES  ('Jijantes FC', 2000000);

COMMIT;

