CREATE OR REPLACE PACKAGE BODY INFORMES AS
    
    PROCEDURE INFORME_EQUIPO (C_INFORME OUT TCURSOR)AS
    BEGIN 
        OPEN C_INFORME FOR 
        SELECT * FROM V_INFO_EQUIPOS;
    END INFORME_EQUIPO;
    
    PROCEDURE INFORME_PARTIDOS_POR_JORNADA (C_PARTIDOS OUT TCURSOR) AS
    BEGIN
        OPEN C_PARTIDOS FOR 
        SELECT * FROM EQUIPOS;
    END INFORME_PARTIDOS_POR_JORNADA;
    
END INFORMES;

