
    
    CREATE OR REPLACE PROCEDURE INFORME_EQUIPO (C_INFORME OUT SYS_REFCURSOR, NOMBRE_EQUIPO IN VARCHAR) AS
        NOMBRE_EQUIPO2 EQUIPOS.NOMBRE%TYPE := NULL;
    BEGIN
        SELECT NOMBRE INTO NOMBRE_EQUIPO2 FROM EQUIPOS WHERE NOMBRE = NOMBRE_EQUIPO;
        OPEN C_INFORME FOR
        -- Se sacarán los datos de la vista V_INFO_EQUIPOS.
        SELECT * FROM V_INFO_EQUIPOS WHERE UPPER(NOMBRE) = UPPER(NOMBRE_EQUIPO);
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                RAISE_APPLICATION_ERROR(-2000, 'NOMBRE DE EQUIPO INCORRECTO');
            WHEN TOO_MANY_ROWS THEN
                RAISE_APPLICATION_ERROR(-2001, 'HAY MAS DE UN EUQIPO CON EL MISMO NOMBRE');
    END INFORME_EQUIPO;
            
/
    
    CREATE OR REPLACE PROCEDURE INFORME_PARTIDOS_POR_JORNADA (C_PARTIDOS OUT SYS_REFCURSOR) AS
        BEGIN
        
            OPEN C_PARTIDOS FOR 
            SELECT
                S.TIPO TIPO_SPLIT,
                J.NUM_JORNADA NUMERO_JORNADA,
                J.TIPO TIPO_JORNADA,
                P.*,
                E1.NOMBRE EQUIPO1,
                E2.NOMBRE EQUIPO2
            FROM SPLITS S, JORNADAS J, PARTIDOS P, EQUIPOS E1, EQUIPOS E2
            WHERE S.ID=J.ID_SPLIT AND J.ID=P.ID_JORNADA 
            AND ID_EQUIPO1 = E1.ID AND ID_EQUIPO2 = E2.ID 
            AND S.ID=(SELECT MAX(ID) FROM SPLITS) ORDER BY J.ID, P.ID;
    END INFORME_PARTIDOS_POR_JORNADA;
    
