CREATE OR REPLACE PACKAGE BODY GESTION_CALENDARIO AS
    -- VERIFICAR QUE SE HAN INTRODUCIDO LOS PLAYOFFS ANTES DE QUE SE INTRODUCCAN EN NUEVAS JORNADAS EN EL SIGUIENTE SPLIT
    PROCEDURE CREAR_SPLIT(TIPO_SPLIT IN VARCHAR) AS 
    BEGIN
        INSERT INTO SPLITS (ANIO, TIPO, ESTADO) VALUES (SYSDATE, TIPO_SPLIT, 'ABIERTO'); 
    END CREAR_SPLIT;
    
    PROCEDURE GENERAR_ENFRENTAMIENTOS AS
        FECHA_PARTIDO DATE := SYSDATE + (7 - TO_NUMBER(TO_CHAR(SYSDATE, 'D')));
        JORNADA_ID NUMBER(3);
        COMPROBADOR NUMBER(3);
        CONT_PARTIDO NUMBER(3);
        CONT_JORNADA NUMBER(2) := 1;
        SPLIT_ID NUMBER(2);
        ID_PARTIDOS NUMBER(3) := 1;
    BEGIN
      SELECT MAX(ID) INTO SPLIT_ID FROM SPLITS;
      SELECT COUNT(*) INTO COMPROBADOR FROM JORNADAS WHERE ID_SPLIT = SPLIT_ID;
      IF COMPROBADOR = 0 THEN 
        INSERT INTO PARTIDOS_HISTORIAL (GOLES_EQUIPO1, GOLES_EQUIPO2, FECHA, LUGAR, ID_JORNADA, ID_EQUIPO1, ID_EQUIPO2) 
        SELECT GOLES_EQUIPO1, GOLES_EQUIPO2, FECHA, LUGAR, ID_JORNADA, ID_EQUIPO1, ID_EQUIPO2 FROM PARTIDOS;
        UPDATE SPLITS SET ESTADO = 'CERRADO' WHERE ID = SPLIT_ID;
        DELETE FROM PARTIDOS;
        DELETE FROM EMPAREJAMIENTOS;
        FOR EQUIPO1 IN (SELECT ID FROM EQUIPOS) LOOP
            FOR EQUIPO2 IN (SELECT ID FROM EQUIPOS WHERE ID != EQUIPO1.ID) LOOP
                SELECT COUNT(*) INTO COMPROBADOR FROM emparejamientos
                    WHERE (ID1 = EQUIPO1.ID AND ID2 = EQUIPO2.ID) 
                    OR (ID1 = EQUIPO2.ID AND ID2 = EQUIPO1.ID);
                IF (COMPROBADOR = 0) THEN
                    INSERT INTO EMPAREJAMIENTOS VALUES (EQUIPO1.ID, EQUIPO2.ID);
                END IF;
            END LOOP;
        END LOOP;
        INSERT INTO JORNADAS (NUM_JORNADA, TIPO, ID_SPLIT) 
        VALUES (CONT_JORNADA,'NORMAL', SPLIT_ID);
        WHILE CONT_JORNADA <= 11 LOOP 
            SELECT MAX(ID) INTO JORNADA_ID FROM JORNADAS;
            CONT_PARTIDO := 0; 
            FOR PAREJA IN (SELECT * FROM EMPAREJAMIENTOS ORDER BY DBMS_RANDOM.VALUE) LOOP
                SELECT COUNT(*) INTO COMPROBADOR FROM PARTIDOS, JORNADAS
                    WHERE (((   ID_EQUIPO1 = PAREJA.ID1) 
                            OR (ID_EQUIPO2 = PAREJA.ID1)
                            OR (ID_EQUIPO1 = PAREJA.ID2) 
                            OR (ID_EQUIPO2 = PAREJA.ID2))
                                AND ID_JORNADA = JORNADA_ID)
                        OR    
                          (((  ID_EQUIPO1 = PAREJA.ID2 AND ID_EQUIPO2 = PAREJA.ID1) 
                           OR (ID_EQUIPO1 = PAREJA.ID1 AND ID_EQUIPO2 = PAREJA.ID2))
                                AND ID_JORNADA = JORNADAS.ID AND ID_SPLIT = SPLIT_ID);
                IF COMPROBADOR = 0 THEN
                    INSERT INTO PARTIDOS(ID, FECHA, LUGAR, ID_JORNADA, ID_EQUIPO1, ID_EQUIPO2) 
                    VALUES (ID_PARTIDOS, FECHA_PARTIDO,'CUPRA ARENA', JORNADA_ID, PAREJA.ID1, PAREJA.ID2);
                    CONT_PARTIDO := CONT_PARTIDO + 1;
                    ID_PARTIDOS := ID_PARTIDOS + 1;
                END IF;
            END LOOP;
            DBMS_OUTPUT.PUT_LINE(CONT_PARTIDO || ' ' || CONT_JORNADA);
            IF CONT_PARTIDO = 6 THEN
                FECHA_PARTIDO := FECHA_PARTIDO + 7;
                CONT_JORNADA := CONT_JORNADA + 1;
                IF CONT_JORNADA <= 11 THEN 
                    INSERT INTO JORNADAS (NUM_JORNADA, TIPO, ID_SPLIT) 
                    VALUES (CONT_JORNADA,'NORMAL',SPLIT_ID);
                END IF;
            ELSE 
                DELETE FROM PARTIDOS WHERE ID_JORNADA = JORNADA_ID;
            END IF;
        END LOOP;
      ELSE
        DBMS_OUTPUT.PUT_LINE('SE TIENE QUE CREAR EL SPLIT ANTES DE GENERAR JORNADAS');
        DBMS_OUTPUT.PUT_LINE('USA EL PROCEDIMIENTO CREAR_SPLIT');
      END IF;
        EXCEPTION
         WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
            DBMS_OUTPUT.PUT_LINE(DBMS_UTILITY.FORMAT_ERROR_STACK());
            DBMS_OUTPUT.PUT_LINE('INTENTALO DE NUEVEO');
            DELETE FROM JORNADAS WHERE ID_SPLIT = SPLIT_ID;
            GESTION_CALENDARIO.GENERAR_ENFRENTAMIENTOS;
    END GENERAR_ENFRENTAMIENTOS;
    
END GESTION_CALENDARIO;
