CREATE OR REPLACE PACKAGE BODY GESTION_CALENDARIO AS
    
    PROCEDURE GENERAR_ENFRENTAMIENTOS AS
        FECHA_PARTIDO DATE := SYSDATE + (7 - TO_NUMBER(TO_CHAR(SYSDATE, 'D')));
        JORNADA_ID NUMBER(3);
        PARTIDO_JUGADO NUMBER(1);
        CONT NUMBER(2) := 1;
    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE EMPAREJAMIENTOS';
        EXECUTE IMMEDIATE 'CREATE GLOBAL TEMPORARY TABLE EMPAREJAMIENTOS (
                      ID1 VARCHAR2(50),
                      ID2 VARCHAR2(50)
                    )';
        FOR EQUIPO1 IN (SELECT ID FROM EQUIPOS) LOOP
            FOR EQUIPO2 IN (SELECT ID FROM EQUIPOS WHERE ID != EQUIPO1.ID) LOOP
                SELECT COUNT(*) INTO PARTIDO_JUGADO FROM emparejamientos
                    WHERE (ID1 = EQUIPO1.ID AND ID2 = EQUIPO2.ID) 
                    OR (ID1 = EQUIPO2.ID AND ID2 = EQUIPO1.ID);
                IF (PARTIDO_JUGADO = 0) THEN
                    INSERT INTO EMPAREJAMIENTOS VALUES (EQUIPO1.ID, EQUIPO2.ID);
                END IF;
            END LOOP;
        END LOOP;
        FOR I IN 1..11 LOOP
            INSERT INTO JORNADAS (NUM_JORNADA, TIPO, ID_SPLIT) VALUES (I,'NORMAL',(SELECT MAX(ID) FROM SPLIT)); 
            SELECT MAX(ID) INTO JORNADA_ID FROM JORNADAS; 
            FOR PAREJA IN (SELECT * FROM EMPAREJAMIENTOS ORDER BY DBMS_RANDOM.VALUE) LOOP
                SELECT COUNT(*) INTO PARTIDO_JUGADO FROM PARTIDOS
                    WHERE (ID_EQUIPO1 = PAREJA.ID1 AND ID_JORNADA = JORNADA_ID) 
                    OR    (ID_EQUIPO2 = PAREJA.ID1 AND ID_JORNADA = JORNADA_ID)
                    OR    (ID_EQUIPO1 = PAREJA.ID2 AND ID_JORNADA = JORNADA_ID) 
                    OR    (ID_EQUIPO2 = PAREJA.ID2 AND ID_JORNADA = JORNADA_ID);
                IF PARTIDO_JUGADO = 0 THEN
                    INSERT INTO PARTIDOS (FECHA, LUGAR, ID_JORNADA, ID_EQUIPO1, ID_EQUIPO2) 
                    VALUES (FECHA_PARTIDO,'SI', JORNADA_ID, PAREJA.ID1, PAREJA.ID2);
                    DELETE FROM EMPAREJAMIENTOS WHERE ID1 = PAREJA.ID1 AND ID2 = PAREJA.ID2;
                    CONT := CONT + 1;
                END IF;
                IF CONT = 7 THEN
                    EXIT;
                END IF;
            END LOOP;
            IF CONT = 7 THEN 
                COMMIT;
            ELSE             
                ROLLBACK;
            END IF;
            CONT := 0;
            FECHA_PARTIDO := FECHA_PARTIDO + 7;
        END LOOP;
        
        EXCEPTION
         WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
            DBMS_OUTPUT.PUT_LINE(DBMS_UTILITY.FORMAT_ERROR_STACK());
    END GENERAR_ENFRENTAMIENTOS;
    
END GESTION_CALENDARIO;