SELECT * FROM CLIENTES WHERE ROWNUM <= 37 ORDER BY codigocliente ASC;


SELECT CONSTRAINT_NAME, TABLE_NAME FROM user_constraints WHERE UPPER(CONSTRAINT_NAME) = 'PAR_ID_PK';

DROP TABLE CALENDARIO_PAREJAS03;

INSERT INTO EQUIPOS (NOMBRE, PRESUPUESTO_ANUAL)
VALUES ('Saiyans FC', 2000000);
INSERT INTO EQUIPOS (NOMBRE, PRESUPUESTO_ANUAL)
VALUES ('Ultimate Móstoles', 2000000);
INSERT INTO EQUIPOS (NOMBRE, PRESUPUESTO_ANUAL)
VALUES ('El Barrio', 2000000);
INSERT INTO EQUIPOS (NOMBRE, PRESUPUESTO_ANUAL)
VALUES ('Kunisports', 2000000);
INSERT INTO EQUIPOS (NOMBRE, PRESUPUESTO_ANUAL)
VALUES ('PIO FC', 2000000);
INSERT INTO EQUIPOS (NOMBRE, PRESUPUESTO_ANUAL)
VALUES ('Aniquiladores FC', 2000000);
INSERT INTO EQUIPOS (NOMBRE, PRESUPUESTO_ANUAL)
VALUES ('Los Troncos FC', 2000000);
INSERT INTO EQUIPOS (NOMBRE, PRESUPUESTO_ANUAL)
VALUES ('1K FC', 2000000);
INSERT INTO EQUIPOS (NOMBRE, PRESUPUESTO_ANUAL)
VALUES ('Rayo de Barcelona', 2000000);
INSERT INTO EQUIPOS (NOMBRE, PRESUPUESTO_ANUAL)
VALUES ('xBuyer Team', 2000000);
INSERT INTO EQUIPOS (NOMBRE, PRESUPUESTO_ANUAL)
VALUES ('Rayoc de Barcelona', 2000000);
INSERT INTO EQUIPOS (NOMBRE, PRESUPUESTO_ANUAL)
VALUES ('Jijantes FC', 2000000);

SELECT * FROM EQUIPOS;
