CREATE OR REPLACE PACKAGE INFORMES AS
    TYPE TCURSOR IS REF CURSOR;
    PROCEDURE INFORME_EQUIPO (C_INFORME OUT TCURSOR);
    PROCEDURE INFORME_PARTIDOS_POR_JORNADA (C_PARTIDOS OUT TCURSOR);
END INFORMES;