CREATE OR REPLACE PACKAGE BODY GESTION_CALENDARIO AS

    PROCEDURE GENERAR_ENFRENTAMIENTOS AS
        FECHA_PARTIDO DATE := SYSDATE + (7 - TO_NUMBER(TO_CHAR(SYSDATE, 'D')));
        JORNADA_ID NUMBER(3);
        PARTIDO_JUGADO NUMBER(1);
        CONT NUMBER(2) := 1;
    BEGIN
        FOR I IN 1..11 LOOP
            INSERT INTO JORNADAS (NUM_JORNADA, TIPO, ID_SPLIT) VALUES (I,'NORMAL',(SELECT MAX(ID) FROM SPLIT));       
        END LOOP;
        SELECT MAX(ID) INTO JORNADA_ID FROM JORNADAS;
        JORNADA_ID := JORNADA_ID - 10;
        FOR EQUIPO1 IN (SELECT ID FROM EQUIPOS ORDER BY ID DESC) LOOP
            FOR EQUIPO2 IN (SELECT ID FROM EQUIPOS WHERE ROWNUM <= (12 - CONT) ORDER BY ID ASC) LOOP
                SELECT COUNT(*) INTO PARTIDO_JUGADO FROM PARTIDOS
                WHERE (ID_EQUIPO1 = EQUIPO1.ID AND ID_JORNADA = JORNADA_ID) 
                OR (ID_EQUIPO2 = EQUIPO1.ID AND ID_JORNADA = JORNADA_ID)
                OR (ID_EQUIPO1 = EQUIPO2.ID AND ID_JORNADA = JORNADA_ID) 
                OR (ID_EQUIPO2 = EQUIPO2.ID AND ID_JORNADA = JORNADA_ID);
                IF (PARTIDO_JUGADO = 0) THEN
                    INSERT INTO PARTIDOS (FECHA, LUGAR, ID_JORNADA, ID_EQUIPO1, ID_EQUIPO2) 
                    VALUES (FECHA_PARTIDO,'SI', JORNADA_ID, EQUIPO1.ID, EQUIPO2.ID);
                    FECHA_PARTIDO := FECHA_PARTIDO + 7;
                    JORNADA_ID := JORNADA_ID + 1;
                    
                END IF; 
            END LOOP;
            CONT := CONT + 1;
            FECHA_PARTIDO := FECHA_PARTIDO - (7 * (11));
            JORNADA_ID := JORNADA_ID - 11;
        END LOOP;
        EXCEPTION
         WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
            DBMS_OUTPUT.PUT_LINE(DBMS_UTILITY.FORMAT_ERROR_STACK());
    END GENERAR_ENFRENTAMIENTOS;
    
END GESTION_CALENDARIO;